[workspace]
members = [
    "game", "server", "shared",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bevy = "0.12.1"
bevy_quinnet = "0.6"
serde = "1.0.198"
shared = { path = "./shared" }