[workspace]
members = [
    "game",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
bevy = "0.12.1"
[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
